name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Or your desired PHP version
          extensions: mbstring, xml, ctype, iconv, pdo_sqlite, dom, filter, gd, json, mysql, pdo_mysql, pdo_pgsql, pdo_sqlite, session, simplexml, sqlite3, tokenizer, zip
          ini-values: memory_limit=-1
          coverage: none # Or xdebug/pcov if you need coverage

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
